################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (9-2020-q2-update)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
C://gitProject/SensiBLE2.1/Library/SDK_Eval_BlueNRG1/src/LPS25HB.c \
C://gitProject/SensiBLE2.1/Library/SDK_Eval_BlueNRG1/src/LSM6DS3.c \
C://gitProject/SensiBLE2.1/Library/SDK_Eval_BlueNRG1/src/SDK_EVAL_Button.c \
C://gitProject/SensiBLE2.1/Library/SDK_Eval_BlueNRG1/src/SDK_EVAL_Com.c \
C://gitProject/SensiBLE2.1/Library/SDK_Eval_BlueNRG1/src/SDK_EVAL_Config.c \
C://gitProject/SensiBLE2.1/Library/SDK_Eval_BlueNRG1/src/SDK_EVAL_Led.c \
C://gitProject/SensiBLE2.1/Library/SDK_Eval_BlueNRG1/src/SDK_EVAL_SPI.c 

OBJS += \
./Platform_Layers/LPS25HB.o \
./Platform_Layers/LSM6DS3.o \
./Platform_Layers/SDK_EVAL_Button.o \
./Platform_Layers/SDK_EVAL_Com.o \
./Platform_Layers/SDK_EVAL_Config.o \
./Platform_Layers/SDK_EVAL_Led.o \
./Platform_Layers/SDK_EVAL_SPI.o 

C_DEPS += \
./Platform_Layers/LPS25HB.d \
./Platform_Layers/LSM6DS3.d \
./Platform_Layers/SDK_EVAL_Button.d \
./Platform_Layers/SDK_EVAL_Com.d \
./Platform_Layers/SDK_EVAL_Config.d \
./Platform_Layers/SDK_EVAL_Led.d \
./Platform_Layers/SDK_EVAL_SPI.d 


# Each subdirectory must supply rules for building sources it contributes
Platform_Layers/LPS25HB.o: C://gitProject/SensiBLE2.1/Library/SDK_Eval_BlueNRG1/src/LPS25HB.c Platform_Layers/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0 -std=c99 -g '-D__weak=__attribute__((weak))' -DHS_SPEED_XTAL=HS_SPEED_XTAL_32MHZ -DLS_SOURCE=LS_SOURCE_EXTERNAL_32KHZ -DSMPS_INDUCTOR=SMPS_INDUCTOR_10uH -DSENSIBLE_2_1 -DIKS01A1 -DBLUENRG2_DEVICE -DSENSOR_EMULATION=1 -DST_OTA_LOWER_APPLICATION=1 -DFORCE_CORE_TO_16MHZ=1 -c -I../../../../../../Drivers/BSP/Components/Common -I../../../../../../Drivers/BSP/Components/at25xe041b -I../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../Drivers/BSP/Components/lis2dw12 -I../../../../../../Drivers/BSP/Components/lis2mdl -I../../../../../../Drivers/BSP/Components/lps25hb -I../../../../../../Drivers/BSP/Components/veml6075 -I../../../../../../Drivers/BSP/STEVAL-BLUEMIC1 -I../../../../../../Drivers/BSP/Sensible20 -I../../../../../../Library/BLE_Application/OTA/inc -I../../../../../../Library/BLE_Application/Utils/inc -I../../../../../../Library/BLE_Application/layers_inc -I../../../../../../Library/BlueNRG1_Periph_Driver/inc -I../../../../../../Library/Bluetooth_LE/inc -I../../../../../../Library/CMSIS/Device/ST/BlueNRG1/Include -I../../../../../../Library/CMSIS/Include -I../../../../../../Library/SDK_Eval_BlueNRG1/inc -I../../../../../../Library/hal/inc -I../../../../../../Middlewares/ST/BlueNRG-1_BlueVoice_Library/Inc -I../../../../../../Middlewares/ST/STM32_MotionMC_Library_2/Inc -I../../../../../../Middlewares/ST/STM32_MotionMC_Library_2/Lib -I../../../inc -Os -ffunction-sections -fdata-sections -Wall -mcpu=cortex-m0 -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Platform_Layers/LSM6DS3.o: C://gitProject/SensiBLE2.1/Library/SDK_Eval_BlueNRG1/src/LSM6DS3.c Platform_Layers/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0 -std=c99 -g '-D__weak=__attribute__((weak))' -DHS_SPEED_XTAL=HS_SPEED_XTAL_32MHZ -DLS_SOURCE=LS_SOURCE_EXTERNAL_32KHZ -DSMPS_INDUCTOR=SMPS_INDUCTOR_10uH -DSENSIBLE_2_1 -DIKS01A1 -DBLUENRG2_DEVICE -DSENSOR_EMULATION=1 -DST_OTA_LOWER_APPLICATION=1 -DFORCE_CORE_TO_16MHZ=1 -c -I../../../../../../Drivers/BSP/Components/Common -I../../../../../../Drivers/BSP/Components/at25xe041b -I../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../Drivers/BSP/Components/lis2dw12 -I../../../../../../Drivers/BSP/Components/lis2mdl -I../../../../../../Drivers/BSP/Components/lps25hb -I../../../../../../Drivers/BSP/Components/veml6075 -I../../../../../../Drivers/BSP/STEVAL-BLUEMIC1 -I../../../../../../Drivers/BSP/Sensible20 -I../../../../../../Library/BLE_Application/OTA/inc -I../../../../../../Library/BLE_Application/Utils/inc -I../../../../../../Library/BLE_Application/layers_inc -I../../../../../../Library/BlueNRG1_Periph_Driver/inc -I../../../../../../Library/Bluetooth_LE/inc -I../../../../../../Library/CMSIS/Device/ST/BlueNRG1/Include -I../../../../../../Library/CMSIS/Include -I../../../../../../Library/SDK_Eval_BlueNRG1/inc -I../../../../../../Library/hal/inc -I../../../../../../Middlewares/ST/BlueNRG-1_BlueVoice_Library/Inc -I../../../../../../Middlewares/ST/STM32_MotionMC_Library_2/Inc -I../../../../../../Middlewares/ST/STM32_MotionMC_Library_2/Lib -I../../../inc -Os -ffunction-sections -fdata-sections -Wall -mcpu=cortex-m0 -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Platform_Layers/SDK_EVAL_Button.o: C://gitProject/SensiBLE2.1/Library/SDK_Eval_BlueNRG1/src/SDK_EVAL_Button.c Platform_Layers/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0 -std=c99 -g '-D__weak=__attribute__((weak))' -DHS_SPEED_XTAL=HS_SPEED_XTAL_32MHZ -DLS_SOURCE=LS_SOURCE_EXTERNAL_32KHZ -DSMPS_INDUCTOR=SMPS_INDUCTOR_10uH -DSENSIBLE_2_1 -DIKS01A1 -DBLUENRG2_DEVICE -DSENSOR_EMULATION=1 -DST_OTA_LOWER_APPLICATION=1 -DFORCE_CORE_TO_16MHZ=1 -c -I../../../../../../Drivers/BSP/Components/Common -I../../../../../../Drivers/BSP/Components/at25xe041b -I../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../Drivers/BSP/Components/lis2dw12 -I../../../../../../Drivers/BSP/Components/lis2mdl -I../../../../../../Drivers/BSP/Components/lps25hb -I../../../../../../Drivers/BSP/Components/veml6075 -I../../../../../../Drivers/BSP/STEVAL-BLUEMIC1 -I../../../../../../Drivers/BSP/Sensible20 -I../../../../../../Library/BLE_Application/OTA/inc -I../../../../../../Library/BLE_Application/Utils/inc -I../../../../../../Library/BLE_Application/layers_inc -I../../../../../../Library/BlueNRG1_Periph_Driver/inc -I../../../../../../Library/Bluetooth_LE/inc -I../../../../../../Library/CMSIS/Device/ST/BlueNRG1/Include -I../../../../../../Library/CMSIS/Include -I../../../../../../Library/SDK_Eval_BlueNRG1/inc -I../../../../../../Library/hal/inc -I../../../../../../Middlewares/ST/BlueNRG-1_BlueVoice_Library/Inc -I../../../../../../Middlewares/ST/STM32_MotionMC_Library_2/Inc -I../../../../../../Middlewares/ST/STM32_MotionMC_Library_2/Lib -I../../../inc -Os -ffunction-sections -fdata-sections -Wall -mcpu=cortex-m0 -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Platform_Layers/SDK_EVAL_Com.o: C://gitProject/SensiBLE2.1/Library/SDK_Eval_BlueNRG1/src/SDK_EVAL_Com.c Platform_Layers/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0 -std=c99 -g '-D__weak=__attribute__((weak))' -DHS_SPEED_XTAL=HS_SPEED_XTAL_32MHZ -DLS_SOURCE=LS_SOURCE_EXTERNAL_32KHZ -DSMPS_INDUCTOR=SMPS_INDUCTOR_10uH -DSENSIBLE_2_1 -DIKS01A1 -DBLUENRG2_DEVICE -DSENSOR_EMULATION=1 -DST_OTA_LOWER_APPLICATION=1 -DFORCE_CORE_TO_16MHZ=1 -c -I../../../../../../Drivers/BSP/Components/Common -I../../../../../../Drivers/BSP/Components/at25xe041b -I../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../Drivers/BSP/Components/lis2dw12 -I../../../../../../Drivers/BSP/Components/lis2mdl -I../../../../../../Drivers/BSP/Components/lps25hb -I../../../../../../Drivers/BSP/Components/veml6075 -I../../../../../../Drivers/BSP/STEVAL-BLUEMIC1 -I../../../../../../Drivers/BSP/Sensible20 -I../../../../../../Library/BLE_Application/OTA/inc -I../../../../../../Library/BLE_Application/Utils/inc -I../../../../../../Library/BLE_Application/layers_inc -I../../../../../../Library/BlueNRG1_Periph_Driver/inc -I../../../../../../Library/Bluetooth_LE/inc -I../../../../../../Library/CMSIS/Device/ST/BlueNRG1/Include -I../../../../../../Library/CMSIS/Include -I../../../../../../Library/SDK_Eval_BlueNRG1/inc -I../../../../../../Library/hal/inc -I../../../../../../Middlewares/ST/BlueNRG-1_BlueVoice_Library/Inc -I../../../../../../Middlewares/ST/STM32_MotionMC_Library_2/Inc -I../../../../../../Middlewares/ST/STM32_MotionMC_Library_2/Lib -I../../../inc -Os -ffunction-sections -fdata-sections -Wall -mcpu=cortex-m0 -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Platform_Layers/SDK_EVAL_Config.o: C://gitProject/SensiBLE2.1/Library/SDK_Eval_BlueNRG1/src/SDK_EVAL_Config.c Platform_Layers/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0 -std=c99 -g '-D__weak=__attribute__((weak))' -DHS_SPEED_XTAL=HS_SPEED_XTAL_32MHZ -DLS_SOURCE=LS_SOURCE_EXTERNAL_32KHZ -DSMPS_INDUCTOR=SMPS_INDUCTOR_10uH -DSENSIBLE_2_1 -DIKS01A1 -DBLUENRG2_DEVICE -DSENSOR_EMULATION=1 -DST_OTA_LOWER_APPLICATION=1 -DFORCE_CORE_TO_16MHZ=1 -c -I../../../../../../Drivers/BSP/Components/Common -I../../../../../../Drivers/BSP/Components/at25xe041b -I../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../Drivers/BSP/Components/lis2dw12 -I../../../../../../Drivers/BSP/Components/lis2mdl -I../../../../../../Drivers/BSP/Components/lps25hb -I../../../../../../Drivers/BSP/Components/veml6075 -I../../../../../../Drivers/BSP/STEVAL-BLUEMIC1 -I../../../../../../Drivers/BSP/Sensible20 -I../../../../../../Library/BLE_Application/OTA/inc -I../../../../../../Library/BLE_Application/Utils/inc -I../../../../../../Library/BLE_Application/layers_inc -I../../../../../../Library/BlueNRG1_Periph_Driver/inc -I../../../../../../Library/Bluetooth_LE/inc -I../../../../../../Library/CMSIS/Device/ST/BlueNRG1/Include -I../../../../../../Library/CMSIS/Include -I../../../../../../Library/SDK_Eval_BlueNRG1/inc -I../../../../../../Library/hal/inc -I../../../../../../Middlewares/ST/BlueNRG-1_BlueVoice_Library/Inc -I../../../../../../Middlewares/ST/STM32_MotionMC_Library_2/Inc -I../../../../../../Middlewares/ST/STM32_MotionMC_Library_2/Lib -I../../../inc -Os -ffunction-sections -fdata-sections -Wall -mcpu=cortex-m0 -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Platform_Layers/SDK_EVAL_Led.o: C://gitProject/SensiBLE2.1/Library/SDK_Eval_BlueNRG1/src/SDK_EVAL_Led.c Platform_Layers/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0 -std=c99 -g '-D__weak=__attribute__((weak))' -DHS_SPEED_XTAL=HS_SPEED_XTAL_32MHZ -DLS_SOURCE=LS_SOURCE_EXTERNAL_32KHZ -DSMPS_INDUCTOR=SMPS_INDUCTOR_10uH -DSENSIBLE_2_1 -DIKS01A1 -DBLUENRG2_DEVICE -DSENSOR_EMULATION=1 -DST_OTA_LOWER_APPLICATION=1 -DFORCE_CORE_TO_16MHZ=1 -c -I../../../../../../Drivers/BSP/Components/Common -I../../../../../../Drivers/BSP/Components/at25xe041b -I../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../Drivers/BSP/Components/lis2dw12 -I../../../../../../Drivers/BSP/Components/lis2mdl -I../../../../../../Drivers/BSP/Components/lps25hb -I../../../../../../Drivers/BSP/Components/veml6075 -I../../../../../../Drivers/BSP/STEVAL-BLUEMIC1 -I../../../../../../Drivers/BSP/Sensible20 -I../../../../../../Library/BLE_Application/OTA/inc -I../../../../../../Library/BLE_Application/Utils/inc -I../../../../../../Library/BLE_Application/layers_inc -I../../../../../../Library/BlueNRG1_Periph_Driver/inc -I../../../../../../Library/Bluetooth_LE/inc -I../../../../../../Library/CMSIS/Device/ST/BlueNRG1/Include -I../../../../../../Library/CMSIS/Include -I../../../../../../Library/SDK_Eval_BlueNRG1/inc -I../../../../../../Library/hal/inc -I../../../../../../Middlewares/ST/BlueNRG-1_BlueVoice_Library/Inc -I../../../../../../Middlewares/ST/STM32_MotionMC_Library_2/Inc -I../../../../../../Middlewares/ST/STM32_MotionMC_Library_2/Lib -I../../../inc -Os -ffunction-sections -fdata-sections -Wall -mcpu=cortex-m0 -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Platform_Layers/SDK_EVAL_SPI.o: C://gitProject/SensiBLE2.1/Library/SDK_Eval_BlueNRG1/src/SDK_EVAL_SPI.c Platform_Layers/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0 -std=c99 -g '-D__weak=__attribute__((weak))' -DHS_SPEED_XTAL=HS_SPEED_XTAL_32MHZ -DLS_SOURCE=LS_SOURCE_EXTERNAL_32KHZ -DSMPS_INDUCTOR=SMPS_INDUCTOR_10uH -DSENSIBLE_2_1 -DIKS01A1 -DBLUENRG2_DEVICE -DSENSOR_EMULATION=1 -DST_OTA_LOWER_APPLICATION=1 -DFORCE_CORE_TO_16MHZ=1 -c -I../../../../../../Drivers/BSP/Components/Common -I../../../../../../Drivers/BSP/Components/at25xe041b -I../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../Drivers/BSP/Components/lis2dw12 -I../../../../../../Drivers/BSP/Components/lis2mdl -I../../../../../../Drivers/BSP/Components/lps25hb -I../../../../../../Drivers/BSP/Components/veml6075 -I../../../../../../Drivers/BSP/STEVAL-BLUEMIC1 -I../../../../../../Drivers/BSP/Sensible20 -I../../../../../../Library/BLE_Application/OTA/inc -I../../../../../../Library/BLE_Application/Utils/inc -I../../../../../../Library/BLE_Application/layers_inc -I../../../../../../Library/BlueNRG1_Periph_Driver/inc -I../../../../../../Library/Bluetooth_LE/inc -I../../../../../../Library/CMSIS/Device/ST/BlueNRG1/Include -I../../../../../../Library/CMSIS/Include -I../../../../../../Library/SDK_Eval_BlueNRG1/inc -I../../../../../../Library/hal/inc -I../../../../../../Middlewares/ST/BlueNRG-1_BlueVoice_Library/Inc -I../../../../../../Middlewares/ST/STM32_MotionMC_Library_2/Inc -I../../../../../../Middlewares/ST/STM32_MotionMC_Library_2/Lib -I../../../inc -Os -ffunction-sections -fdata-sections -Wall -mcpu=cortex-m0 -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"

