################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (9-2020-q2-update)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
C://gitProject/SensiBLE2.1/Project/BLE_Examples/BLE_SensorDemo/src/BlueNRG1_it.c \
C://gitProject/SensiBLE2.1/Project/BLE_Examples/BLE_SensorDemo/src/HWAdvanceFeatures.c \
C://gitProject/SensiBLE2.1/Project/BLE_Examples/BLE_SensorDemo/src/acceleroSamplesProcessing.c \
C://gitProject/SensiBLE2.1/Project/BLE_Examples/BLE_SensorDemo/src/bluevoice_app.c \
C://gitProject/SensiBLE2.1/Project/BLE_Examples/BLE_SensorDemo/src/inertial_app.c \
C://gitProject/SensiBLE2.1/Project/BLE_Examples/BLE_SensorDemo/src/main.c \
C://gitProject/SensiBLE2.1/Project/BLE_Examples/BLE_SensorDemo/src/peripheral_mngr_app.c \
C://gitProject/SensiBLE2.1/Project/BLE_Examples/BLE_SensorDemo/src/sensible_sensors.c \
C://gitProject/SensiBLE2.1/Project/BLE_Examples/BLE_SensorDemo/src/sensible_services.c 

OBJS += \
./User/src/BlueNRG1_it.o \
./User/src/HWAdvanceFeatures.o \
./User/src/acceleroSamplesProcessing.o \
./User/src/bluevoice_app.o \
./User/src/inertial_app.o \
./User/src/main.o \
./User/src/peripheral_mngr_app.o \
./User/src/sensible_sensors.o \
./User/src/sensible_services.o 

C_DEPS += \
./User/src/BlueNRG1_it.d \
./User/src/HWAdvanceFeatures.d \
./User/src/acceleroSamplesProcessing.d \
./User/src/bluevoice_app.d \
./User/src/inertial_app.d \
./User/src/main.d \
./User/src/peripheral_mngr_app.d \
./User/src/sensible_sensors.d \
./User/src/sensible_services.d 


# Each subdirectory must supply rules for building sources it contributes
User/src/BlueNRG1_it.o: C://gitProject/SensiBLE2.1/Project/BLE_Examples/BLE_SensorDemo/src/BlueNRG1_it.c User/src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0 -std=c99 -g '-D__weak=__attribute__((weak))' -DHS_SPEED_XTAL=HS_SPEED_XTAL_32MHZ -DLS_SOURCE=LS_SOURCE_EXTERNAL_32KHZ -DSMPS_INDUCTOR=SMPS_INDUCTOR_10uH -DSENSIBLE_2_1 -DIKS01A1 -DBLUENRG2_DEVICE -DSENSOR_EMULATION=1 -DST_OTA_LOWER_APPLICATION=1 -DFORCE_CORE_TO_16MHZ=1 -c -I../../../../../../Drivers/BSP/Components/Common -I../../../../../../Drivers/BSP/Components/at25xe041b -I../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../Drivers/BSP/Components/lis2dw12 -I../../../../../../Drivers/BSP/Components/lis2mdl -I../../../../../../Drivers/BSP/Components/lps25hb -I../../../../../../Drivers/BSP/Components/veml6075 -I../../../../../../Drivers/BSP/STEVAL-BLUEMIC1 -I../../../../../../Drivers/BSP/Sensible20 -I../../../../../../Library/BLE_Application/OTA/inc -I../../../../../../Library/BLE_Application/Utils/inc -I../../../../../../Library/BLE_Application/layers_inc -I../../../../../../Library/BlueNRG1_Periph_Driver/inc -I../../../../../../Library/Bluetooth_LE/inc -I../../../../../../Library/CMSIS/Device/ST/BlueNRG1/Include -I../../../../../../Library/CMSIS/Include -I../../../../../../Library/SDK_Eval_BlueNRG1/inc -I../../../../../../Library/hal/inc -I../../../../../../Middlewares/ST/BlueNRG-1_BlueVoice_Library/Inc -I../../../../../../Middlewares/ST/STM32_MotionMC_Library_2/Inc -I../../../../../../Middlewares/ST/STM32_MotionMC_Library_2/Lib -I../../../inc -Os -ffunction-sections -fdata-sections -Wall -mcpu=cortex-m0 -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
User/src/HWAdvanceFeatures.o: C://gitProject/SensiBLE2.1/Project/BLE_Examples/BLE_SensorDemo/src/HWAdvanceFeatures.c User/src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0 -std=c99 -g '-D__weak=__attribute__((weak))' -DHS_SPEED_XTAL=HS_SPEED_XTAL_32MHZ -DLS_SOURCE=LS_SOURCE_EXTERNAL_32KHZ -DSMPS_INDUCTOR=SMPS_INDUCTOR_10uH -DSENSIBLE_2_1 -DIKS01A1 -DBLUENRG2_DEVICE -DSENSOR_EMULATION=1 -DST_OTA_LOWER_APPLICATION=1 -DFORCE_CORE_TO_16MHZ=1 -c -I../../../../../../Drivers/BSP/Components/Common -I../../../../../../Drivers/BSP/Components/at25xe041b -I../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../Drivers/BSP/Components/lis2dw12 -I../../../../../../Drivers/BSP/Components/lis2mdl -I../../../../../../Drivers/BSP/Components/lps25hb -I../../../../../../Drivers/BSP/Components/veml6075 -I../../../../../../Drivers/BSP/STEVAL-BLUEMIC1 -I../../../../../../Drivers/BSP/Sensible20 -I../../../../../../Library/BLE_Application/OTA/inc -I../../../../../../Library/BLE_Application/Utils/inc -I../../../../../../Library/BLE_Application/layers_inc -I../../../../../../Library/BlueNRG1_Periph_Driver/inc -I../../../../../../Library/Bluetooth_LE/inc -I../../../../../../Library/CMSIS/Device/ST/BlueNRG1/Include -I../../../../../../Library/CMSIS/Include -I../../../../../../Library/SDK_Eval_BlueNRG1/inc -I../../../../../../Library/hal/inc -I../../../../../../Middlewares/ST/BlueNRG-1_BlueVoice_Library/Inc -I../../../../../../Middlewares/ST/STM32_MotionMC_Library_2/Inc -I../../../../../../Middlewares/ST/STM32_MotionMC_Library_2/Lib -I../../../inc -Os -ffunction-sections -fdata-sections -Wall -mcpu=cortex-m0 -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
User/src/acceleroSamplesProcessing.o: C://gitProject/SensiBLE2.1/Project/BLE_Examples/BLE_SensorDemo/src/acceleroSamplesProcessing.c User/src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0 -std=c99 -g '-D__weak=__attribute__((weak))' -DHS_SPEED_XTAL=HS_SPEED_XTAL_32MHZ -DLS_SOURCE=LS_SOURCE_EXTERNAL_32KHZ -DSMPS_INDUCTOR=SMPS_INDUCTOR_10uH -DSENSIBLE_2_1 -DIKS01A1 -DBLUENRG2_DEVICE -DSENSOR_EMULATION=1 -DST_OTA_LOWER_APPLICATION=1 -DFORCE_CORE_TO_16MHZ=1 -c -I../../../../../../Drivers/BSP/Components/Common -I../../../../../../Drivers/BSP/Components/at25xe041b -I../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../Drivers/BSP/Components/lis2dw12 -I../../../../../../Drivers/BSP/Components/lis2mdl -I../../../../../../Drivers/BSP/Components/lps25hb -I../../../../../../Drivers/BSP/Components/veml6075 -I../../../../../../Drivers/BSP/STEVAL-BLUEMIC1 -I../../../../../../Drivers/BSP/Sensible20 -I../../../../../../Library/BLE_Application/OTA/inc -I../../../../../../Library/BLE_Application/Utils/inc -I../../../../../../Library/BLE_Application/layers_inc -I../../../../../../Library/BlueNRG1_Periph_Driver/inc -I../../../../../../Library/Bluetooth_LE/inc -I../../../../../../Library/CMSIS/Device/ST/BlueNRG1/Include -I../../../../../../Library/CMSIS/Include -I../../../../../../Library/SDK_Eval_BlueNRG1/inc -I../../../../../../Library/hal/inc -I../../../../../../Middlewares/ST/BlueNRG-1_BlueVoice_Library/Inc -I../../../../../../Middlewares/ST/STM32_MotionMC_Library_2/Inc -I../../../../../../Middlewares/ST/STM32_MotionMC_Library_2/Lib -I../../../inc -Os -ffunction-sections -fdata-sections -Wall -mcpu=cortex-m0 -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
User/src/bluevoice_app.o: C://gitProject/SensiBLE2.1/Project/BLE_Examples/BLE_SensorDemo/src/bluevoice_app.c User/src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0 -std=c99 -g '-D__weak=__attribute__((weak))' -DHS_SPEED_XTAL=HS_SPEED_XTAL_32MHZ -DLS_SOURCE=LS_SOURCE_EXTERNAL_32KHZ -DSMPS_INDUCTOR=SMPS_INDUCTOR_10uH -DSENSIBLE_2_1 -DIKS01A1 -DBLUENRG2_DEVICE -DSENSOR_EMULATION=1 -DST_OTA_LOWER_APPLICATION=1 -DFORCE_CORE_TO_16MHZ=1 -c -I../../../../../../Drivers/BSP/Components/Common -I../../../../../../Drivers/BSP/Components/at25xe041b -I../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../Drivers/BSP/Components/lis2dw12 -I../../../../../../Drivers/BSP/Components/lis2mdl -I../../../../../../Drivers/BSP/Components/lps25hb -I../../../../../../Drivers/BSP/Components/veml6075 -I../../../../../../Drivers/BSP/STEVAL-BLUEMIC1 -I../../../../../../Drivers/BSP/Sensible20 -I../../../../../../Library/BLE_Application/OTA/inc -I../../../../../../Library/BLE_Application/Utils/inc -I../../../../../../Library/BLE_Application/layers_inc -I../../../../../../Library/BlueNRG1_Periph_Driver/inc -I../../../../../../Library/Bluetooth_LE/inc -I../../../../../../Library/CMSIS/Device/ST/BlueNRG1/Include -I../../../../../../Library/CMSIS/Include -I../../../../../../Library/SDK_Eval_BlueNRG1/inc -I../../../../../../Library/hal/inc -I../../../../../../Middlewares/ST/BlueNRG-1_BlueVoice_Library/Inc -I../../../../../../Middlewares/ST/STM32_MotionMC_Library_2/Inc -I../../../../../../Middlewares/ST/STM32_MotionMC_Library_2/Lib -I../../../inc -Os -ffunction-sections -fdata-sections -Wall -mcpu=cortex-m0 -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
User/src/inertial_app.o: C://gitProject/SensiBLE2.1/Project/BLE_Examples/BLE_SensorDemo/src/inertial_app.c User/src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0 -std=c99 -g '-D__weak=__attribute__((weak))' -DHS_SPEED_XTAL=HS_SPEED_XTAL_32MHZ -DLS_SOURCE=LS_SOURCE_EXTERNAL_32KHZ -DSMPS_INDUCTOR=SMPS_INDUCTOR_10uH -DSENSIBLE_2_1 -DIKS01A1 -DBLUENRG2_DEVICE -DSENSOR_EMULATION=1 -DST_OTA_LOWER_APPLICATION=1 -DFORCE_CORE_TO_16MHZ=1 -c -I../../../../../../Drivers/BSP/Components/Common -I../../../../../../Drivers/BSP/Components/at25xe041b -I../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../Drivers/BSP/Components/lis2dw12 -I../../../../../../Drivers/BSP/Components/lis2mdl -I../../../../../../Drivers/BSP/Components/lps25hb -I../../../../../../Drivers/BSP/Components/veml6075 -I../../../../../../Drivers/BSP/STEVAL-BLUEMIC1 -I../../../../../../Drivers/BSP/Sensible20 -I../../../../../../Library/BLE_Application/OTA/inc -I../../../../../../Library/BLE_Application/Utils/inc -I../../../../../../Library/BLE_Application/layers_inc -I../../../../../../Library/BlueNRG1_Periph_Driver/inc -I../../../../../../Library/Bluetooth_LE/inc -I../../../../../../Library/CMSIS/Device/ST/BlueNRG1/Include -I../../../../../../Library/CMSIS/Include -I../../../../../../Library/SDK_Eval_BlueNRG1/inc -I../../../../../../Library/hal/inc -I../../../../../../Middlewares/ST/BlueNRG-1_BlueVoice_Library/Inc -I../../../../../../Middlewares/ST/STM32_MotionMC_Library_2/Inc -I../../../../../../Middlewares/ST/STM32_MotionMC_Library_2/Lib -I../../../inc -Os -ffunction-sections -fdata-sections -Wall -mcpu=cortex-m0 -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
User/src/main.o: C://gitProject/SensiBLE2.1/Project/BLE_Examples/BLE_SensorDemo/src/main.c User/src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0 -std=c99 -g '-D__weak=__attribute__((weak))' -DHS_SPEED_XTAL=HS_SPEED_XTAL_32MHZ -DLS_SOURCE=LS_SOURCE_EXTERNAL_32KHZ -DSMPS_INDUCTOR=SMPS_INDUCTOR_10uH -DSENSIBLE_2_1 -DIKS01A1 -DBLUENRG2_DEVICE -DSENSOR_EMULATION=1 -DST_OTA_LOWER_APPLICATION=1 -DFORCE_CORE_TO_16MHZ=1 -c -I../../../../../../Drivers/BSP/Components/Common -I../../../../../../Drivers/BSP/Components/at25xe041b -I../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../Drivers/BSP/Components/lis2dw12 -I../../../../../../Drivers/BSP/Components/lis2mdl -I../../../../../../Drivers/BSP/Components/lps25hb -I../../../../../../Drivers/BSP/Components/veml6075 -I../../../../../../Drivers/BSP/STEVAL-BLUEMIC1 -I../../../../../../Drivers/BSP/Sensible20 -I../../../../../../Library/BLE_Application/OTA/inc -I../../../../../../Library/BLE_Application/Utils/inc -I../../../../../../Library/BLE_Application/layers_inc -I../../../../../../Library/BlueNRG1_Periph_Driver/inc -I../../../../../../Library/Bluetooth_LE/inc -I../../../../../../Library/CMSIS/Device/ST/BlueNRG1/Include -I../../../../../../Library/CMSIS/Include -I../../../../../../Library/SDK_Eval_BlueNRG1/inc -I../../../../../../Library/hal/inc -I../../../../../../Middlewares/ST/BlueNRG-1_BlueVoice_Library/Inc -I../../../../../../Middlewares/ST/STM32_MotionMC_Library_2/Inc -I../../../../../../Middlewares/ST/STM32_MotionMC_Library_2/Lib -I../../../inc -Os -ffunction-sections -fdata-sections -Wall -mcpu=cortex-m0 -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
User/src/peripheral_mngr_app.o: C://gitProject/SensiBLE2.1/Project/BLE_Examples/BLE_SensorDemo/src/peripheral_mngr_app.c User/src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0 -std=c99 -g '-D__weak=__attribute__((weak))' -DHS_SPEED_XTAL=HS_SPEED_XTAL_32MHZ -DLS_SOURCE=LS_SOURCE_EXTERNAL_32KHZ -DSMPS_INDUCTOR=SMPS_INDUCTOR_10uH -DSENSIBLE_2_1 -DIKS01A1 -DBLUENRG2_DEVICE -DSENSOR_EMULATION=1 -DST_OTA_LOWER_APPLICATION=1 -DFORCE_CORE_TO_16MHZ=1 -c -I../../../../../../Drivers/BSP/Components/Common -I../../../../../../Drivers/BSP/Components/at25xe041b -I../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../Drivers/BSP/Components/lis2dw12 -I../../../../../../Drivers/BSP/Components/lis2mdl -I../../../../../../Drivers/BSP/Components/lps25hb -I../../../../../../Drivers/BSP/Components/veml6075 -I../../../../../../Drivers/BSP/STEVAL-BLUEMIC1 -I../../../../../../Drivers/BSP/Sensible20 -I../../../../../../Library/BLE_Application/OTA/inc -I../../../../../../Library/BLE_Application/Utils/inc -I../../../../../../Library/BLE_Application/layers_inc -I../../../../../../Library/BlueNRG1_Periph_Driver/inc -I../../../../../../Library/Bluetooth_LE/inc -I../../../../../../Library/CMSIS/Device/ST/BlueNRG1/Include -I../../../../../../Library/CMSIS/Include -I../../../../../../Library/SDK_Eval_BlueNRG1/inc -I../../../../../../Library/hal/inc -I../../../../../../Middlewares/ST/BlueNRG-1_BlueVoice_Library/Inc -I../../../../../../Middlewares/ST/STM32_MotionMC_Library_2/Inc -I../../../../../../Middlewares/ST/STM32_MotionMC_Library_2/Lib -I../../../inc -Os -ffunction-sections -fdata-sections -Wall -mcpu=cortex-m0 -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
User/src/sensible_sensors.o: C://gitProject/SensiBLE2.1/Project/BLE_Examples/BLE_SensorDemo/src/sensible_sensors.c User/src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0 -std=c99 -g '-D__weak=__attribute__((weak))' -DHS_SPEED_XTAL=HS_SPEED_XTAL_32MHZ -DLS_SOURCE=LS_SOURCE_EXTERNAL_32KHZ -DSMPS_INDUCTOR=SMPS_INDUCTOR_10uH -DSENSIBLE_2_1 -DIKS01A1 -DBLUENRG2_DEVICE -DSENSOR_EMULATION=1 -DST_OTA_LOWER_APPLICATION=1 -DFORCE_CORE_TO_16MHZ=1 -c -I../../../../../../Drivers/BSP/Components/Common -I../../../../../../Drivers/BSP/Components/at25xe041b -I../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../Drivers/BSP/Components/lis2dw12 -I../../../../../../Drivers/BSP/Components/lis2mdl -I../../../../../../Drivers/BSP/Components/lps25hb -I../../../../../../Drivers/BSP/Components/veml6075 -I../../../../../../Drivers/BSP/STEVAL-BLUEMIC1 -I../../../../../../Drivers/BSP/Sensible20 -I../../../../../../Library/BLE_Application/OTA/inc -I../../../../../../Library/BLE_Application/Utils/inc -I../../../../../../Library/BLE_Application/layers_inc -I../../../../../../Library/BlueNRG1_Periph_Driver/inc -I../../../../../../Library/Bluetooth_LE/inc -I../../../../../../Library/CMSIS/Device/ST/BlueNRG1/Include -I../../../../../../Library/CMSIS/Include -I../../../../../../Library/SDK_Eval_BlueNRG1/inc -I../../../../../../Library/hal/inc -I../../../../../../Middlewares/ST/BlueNRG-1_BlueVoice_Library/Inc -I../../../../../../Middlewares/ST/STM32_MotionMC_Library_2/Inc -I../../../../../../Middlewares/ST/STM32_MotionMC_Library_2/Lib -I../../../inc -Os -ffunction-sections -fdata-sections -Wall -mcpu=cortex-m0 -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
User/src/sensible_services.o: C://gitProject/SensiBLE2.1/Project/BLE_Examples/BLE_SensorDemo/src/sensible_services.c User/src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0 -std=c99 -g '-D__weak=__attribute__((weak))' -DHS_SPEED_XTAL=HS_SPEED_XTAL_32MHZ -DLS_SOURCE=LS_SOURCE_EXTERNAL_32KHZ -DSMPS_INDUCTOR=SMPS_INDUCTOR_10uH -DSENSIBLE_2_1 -DIKS01A1 -DBLUENRG2_DEVICE -DSENSOR_EMULATION=1 -DST_OTA_LOWER_APPLICATION=1 -DFORCE_CORE_TO_16MHZ=1 -c -I../../../../../../Drivers/BSP/Components/Common -I../../../../../../Drivers/BSP/Components/at25xe041b -I../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../Drivers/BSP/Components/lis2dw12 -I../../../../../../Drivers/BSP/Components/lis2mdl -I../../../../../../Drivers/BSP/Components/lps25hb -I../../../../../../Drivers/BSP/Components/veml6075 -I../../../../../../Drivers/BSP/STEVAL-BLUEMIC1 -I../../../../../../Drivers/BSP/Sensible20 -I../../../../../../Library/BLE_Application/OTA/inc -I../../../../../../Library/BLE_Application/Utils/inc -I../../../../../../Library/BLE_Application/layers_inc -I../../../../../../Library/BlueNRG1_Periph_Driver/inc -I../../../../../../Library/Bluetooth_LE/inc -I../../../../../../Library/CMSIS/Device/ST/BlueNRG1/Include -I../../../../../../Library/CMSIS/Include -I../../../../../../Library/SDK_Eval_BlueNRG1/inc -I../../../../../../Library/hal/inc -I../../../../../../Middlewares/ST/BlueNRG-1_BlueVoice_Library/Inc -I../../../../../../Middlewares/ST/STM32_MotionMC_Library_2/Inc -I../../../../../../Middlewares/ST/STM32_MotionMC_Library_2/Lib -I../../../inc -Os -ffunction-sections -fdata-sections -Wall -mcpu=cortex-m0 -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"

